const NAME_RE = /^[A-Za-zÀ-ÖØ-öø-ÿ' -]{2,40}$/;
const ALLOWED = new Set(['familia','relacionamento','emprego','financeiro','saude','filhos','emocional','outro']);
function reply(statusCode, body){return {statusCode,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'},body:JSON.stringify(body)}}
function cleanName(v){return String(v||'').trim().replace(/\s+/g,' ').slice(0,40)}
async function readAll(store){const {blobs}=await store.list({prefix:'request/'});const items=[];for(const b of blobs.slice(-200)){const x=await store.get(b.key,{type:'json',consistency:'strong'});if(x)items.push({...x,key:b.key})}items.sort((a,b)=>b.createdAt-a.createdAt);return items}
exports.handler=async(event)=>{const {getStore}=await import('@netlify/blobs');const store=getStore({name:'prayer-wall',consistency:'strong'});
 if(event.httpMethod==='GET'){const items=await readAll(store);const today=Date.now()-86400000;return reply(200,{items:items.slice(0,16).map(({key,firstName,category,createdAt,prayers=0})=>({id:key,firstName,category,createdAt,prayers})),stats:{requests:items.length,today:items.filter(x=>x.createdAt>=today).length,prayers:items.reduce((s,x)=>s+(x.prayers||0),0)}})}
 if(event.httpMethod!=='POST')return reply(405,{error:'Método não permitido.'});let body;try{body=JSON.parse(event.body||'{}')}catch{return reply(400,{error:'Dados inválidos.'})}
 if(body.action==='pray'){const key=String(body.id||'');if(!key.startsWith('request/'))return reply(400,{error:'Pedido inválido.'});const x=await store.get(key,{type:'json',consistency:'strong'});if(!x)return reply(404,{error:'Pedido não encontrado.'});x.prayers=(x.prayers||0)+1;await store.setJSON(key,x);return reply(200,{ok:true,prayers:x.prayers})}
 const firstName=cleanName(body.firstName),category=String(body.category||'');if(!NAME_RE.test(firstName))return reply(400,{error:'Informe apenas seu primeiro nome.'});if(!ALLOWED.has(category))return reply(400,{error:'Escolha uma causa de oração.'});const createdAt=Date.now();const key=`request/${String(createdAt).padStart(13,'0')}-${crypto.randomUUID()}`;await store.setJSON(key,{firstName,category,createdAt,prayers:0});return reply(200,{ok:true,id:key,firstName,category,createdAt,prayers:0})};
