const SHARE_TEXT=`🙏 Estou participando da corrente @123Deus.Sabe.\n\nHá batalhas que ninguém vê. Se existe uma causa no seu coração, você não precisa explicar. Pode apenas dizer: DEUS SABE.\n\nUma corrente continua quando um elo encontra outro. Seja o próximo elo:\n`;
const $=s=>document.querySelector(s);function track(n,p={}){try{if(typeof gtag==='function')gtag('event',n,p)}catch(e){}}function shareUrl(){return location.origin+location.pathname}function setupShare(){$('#whatsappShare').href=`https://wa.me/?text=${encodeURIComponent(SHARE_TEXT+shareUrl())}`}
let selectedCause='';const causeLabels={familia:'Família',relacionamento:'Relacionamento',emprego:'Porta de emprego',financeiro:'Vida financeira',saude:'Saúde',filhos:'Filhos e casa',emocional:'Vida emocional',outro:'Deus sabe'};
document.querySelectorAll('[data-cause]').forEach(btn=>btn.addEventListener('click',()=>{selectedCause=btn.dataset.cause;document.querySelectorAll('[data-cause]').forEach(b=>b.classList.toggle('selected',b===btn));$('#prayerEmailBox').classList.remove('hidden');$('#prayerEmailBox').scrollIntoView({behavior:'smooth',block:'center'});track('causa_oracao_escolhida',{causa:selectedCause})}));
$('#desabafoBtn').addEventListener('click',()=>{$('#desabafo').classList.remove('hidden');$('#desabafo').scrollIntoView({behavior:'smooth'});track('abrir_desabafo')});$('#orarBtn').addEventListener('click',()=>{$('.wall-section').scrollIntoView({behavior:'smooth'});track('orar_por_alguem')});
async function sendLead(email,firstName='Amigo(a)'){const r=await fetch('/.netlify/functions/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName,email,consent:true})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Não foi possível concluir agora.');return j}
async function addPrayer(firstName,category){const r=await fetch('/.netlify/functions/prayers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName,category})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Não foi possível incluir seu nome agora.');return j}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function relativeTime(t){const m=Math.max(0,Math.floor((Date.now()-t)/60000));if(m<1)return'agora';if(m<60)return`há ${m} min`;const h=Math.floor(m/60);if(h<24)return`há ${h}h`;return`há ${Math.floor(h/24)} dia(s)`}
async function prayFor(id,btn){if(btn.dataset.done)return;try{const r=await fetch('/.netlify/functions/prayers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'pray',id})});const j=await r.json();if(!r.ok)throw new Error();btn.dataset.done='1';btn.classList.add('done');btn.innerHTML=`❤️ Você orou • ${j.prayers} ${j.prayers===1?'oração':'orações'}`;track('oracao_por_pessoa');loadWallStatsOnly()}catch{btn.textContent='Tente novamente'}}
function renderStats(s={}){$('#statRequests').textContent=s.requests??0;$('#statPrayers').textContent=s.prayers??0;$('#statToday').textContent=s.today??0}
async function loadWallStatsOnly(){try{const r=await fetch('/.netlify/functions/prayers');const j=await r.json();renderStats(j.stats)}catch{}}
async function loadWall(){const wall=$('#prayerWall');try{const r=await fetch('/.netlify/functions/prayers');const j=await r.json();renderStats(j.stats);if(!j.items?.length){wall.innerHTML='<div class="wall-empty"><strong>Seja o primeiro elo desta corrente. 🙏</strong><br>Quando alguém pedir oração, o nome aparecerá aqui.</div>';return}wall.innerHTML=j.items.map(x=>`<div class="prayer-person"><strong>🙏 ${escapeHtml(x.firstName)}</strong><span class="cause">${escapeHtml(causeLabels[x.category]||'Deus sabe')} • ${relativeTime(x.createdAt)}</span><button class="pray-btn" data-id="${escapeHtml(x.id)}">❤️ OREI POR ${escapeHtml(x.firstName).toUpperCase()} • ${x.prayers||0}</button></div>`).join('');wall.querySelectorAll('.pray-btn').forEach(b=>b.addEventListener('click',()=>prayFor(b.dataset.id,b)))}catch{wall.innerHTML='<div class="wall-empty">A corrente está sendo preparada.</div>'}}
$('#prayerForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('#prayerStatus');if(!selectedCause){st.textContent='Escolha primeiro uma causa.';return}const name=$('#prayerName').value.trim(),email=$('#prayerEmail').value.trim();st.textContent='Ligando seu nome à corrente...';try{await sendLead(email,name);await addPrayer(name,selectedCause);st.innerHTML=`🙏 <strong>${escapeHtml(name)}, você agora é um elo desta corrente.</strong><br>Sua causa entrou no Caderno de Orações. Deus sabe.`;track('pedido_de_oracao',{tipo:selectedCause});await loadWall();setTimeout(()=>$('.wall-section').scrollIntoView({behavior:'smooth'}),1000)}catch(err){st.textContent=err.message}});
$('#desabafoForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('#formStatus');st.textContent='Enviando...';try{await sendLead($('#desabafoEmail').value,'Amigo(a)');st.innerHTML='🙏 <strong>Recebemos seu pedido.</strong> Estamos juntos em oração. Você receberá nossas mensagens de acolhimento no e-mail informado.';track('desabafo_enviado');$('#desabafoTexto').value='';setTimeout(()=>$('#share').scrollIntoView({behavior:'smooth'}),900)}catch(err){st.textContent=err.message}});
$('#emailForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('#emailStatus');st.textContent='Cadastrando...';try{await sendLead($('#emailOnly').value,'Amigo(a)');st.textContent='🙏 Pronto. Vamos continuar juntos nesta corrente.';track('email_cadastrado')}catch(err){st.textContent=err.message}});$('#copyBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText(SHARE_TEXT+shareUrl());$('#copyBtn').textContent='✓ LINK COPIADO';track('compartilhar_copiar')});$('#pixCopy').addEventListener('click',async()=>{await navigator.clipboard.writeText('81996867010');$('#pixCopy').textContent='✓ PIX COPIADO';track('pix_copiado')});$('#whatsappShare').addEventListener('click',()=>track('compartilhar_whatsapp'));setupShare();loadWall();
